
version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: campagne_db
      POSTGRES_USER: seck
      POSTGRES_PASSWORD: 3004
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      PGUSER: seck
      PGPASSWORD: 3004
      PGDATABASE: campagne_db
      PGHOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
