
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build backend Docker image
      run: docker build -f docker/Dockerfile.backend -t backend .

    - name: Build frontend Docker image
      run: docker build -f docker/Dockerfile.frontend -t frontend .

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd campagne-app
          docker-compose down
          docker-compose up -d --build
