name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Build the backend Docker image
    - name: Build backend Docker image
      run: docker build -f docker/Dockerfile.backend -t backend .

    # Build the frontend Docker image
    - name: Build frontend Docker image
      run: docker build -f docker/Dockerfile.frontend -t frontend .

    # Deploy the services to the server
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd campagne-app
          # Stop any existing containers
          sudo docker-compose down
          # Rebuild and start the services
          sudo docker-compose up -d --build
          
    # Verify that the containers are up and running
    - name: Verify services are running
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Check that the containers are running
          docker ps
